## NUMPY library
## use Multi dimensional array
'''
array have collection of same value or objects.
To install numpy library need import pip install numpy.
In anaconda need to use conda install numpy.
'''


In [36]:
# import numpy library
import numpy as np

In [12]:
list_value=[1,2,3,4,5]

In [14]:
type(list_value)

list

In [20]:
arr=np.array(list_value)
arr

array([1, 2, 3, 4, 5])

In [24]:
type(arr)
arr.shape    

(5,)

In [26]:
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [28]:
arr.shape

(5,)

In [32]:
arr1 = arr.reshape(5,1)
arr1.shape

(5, 1)

In [38]:
arr1

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [40]:
## indexing arrar

In [50]:
arr2=np.array([1,2,3,4,5,6,7,8,9])
print(arr2.shape)
arr2[2]

(9,)


3

In [52]:
arr2= arr2.reshape(3,3)

In [54]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr2[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
## array indexing zero is row and column starting position, end position will be counted as numbers starting from 1st position
arr2[0:2,0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
arr2[1:,1:]

array([[5, 6],
       [8, 9]])

In [113]:
#### list1=[1,2,3,4]
list2=[5,6,7,8]
list3=[9,10,11,12]
list4=[13,14,15,16]
arr4 = np.array([list1,list2,list3,list4])
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [115]:
arr4[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [117]:
arr4[1:3,2:4]

array([[ 7,  8],
       [11, 12]])

In [133]:
arr5=np.arange(0,9,step=2)

In [135]:
arr5

array([0, 2, 4, 6, 8])

In [137]:
##copy function
arr5[2:]=10

In [139]:
arr5

array([ 0,  2, 10, 10, 10])

In [141]:
arr5

array([ 0,  2, 10, 10, 10])

In [145]:
arr6= arr5.copy();
arr6[2:]=5
print(arr6)
print(arr5)

[0 2 5 5 5]
[ 0  2 10 10 10]


In [147]:
arr5>2

array([False, False,  True,  True,  True])

In [159]:
arr5[arr5>2]

array([10, 10, 10])

In [205]:
## numpy function of creating random numbers with dimentional arrays
np.ones((5,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [207]:
np.random.rand(3,3)

array([[0.66417284, 0.17446017, 0.27397745],
       [0.22446141, 0.01122732, 0.81059805],
       [0.18769688, 0.26997211, 0.77280337]])

In [209]:
np.random.random_sample((1,5))

array([[0.49351295, 0.29887557, 0.11634718, 0.40859502, 0.73382974]])

In [211]:
np.random.randint(100, size=(2, 4))

array([[89, 61,  0, 65],
       [98, 47, 40, 18]])